spring:
  profiles: 
    active: local
  cloud:
    stream:
      bindings:      
        cargoRoutingChannel:
          destination: cargoRoutings
          group: cargoRoutingsQueue
          contentType: 'application/json'
        cargoHandlingChannel1:
          destination: cargoHandlings1
          group: cargoHandlingsQueue1
          contentType: 'application/json'                                                   
                    
  datasource:
    url: "jdbc:mysql://10.242.0.6:3306/trackingmsdb?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=EST&useSSL=false&allowPublicKeyRetrieval=true"
    username: trackingmsdb
    password: password
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  application:
    name: "${IMAGE_NAME:template-spring-boot}"

swagger:
  baseApiPackage:
  - "com.cargotracker"
  - "com.ibm.health"
  title: "cargo-tracking-service"
  description: "cargo-tracking-service"
  version: "1.0.0"
  termsOfServiceUrl: ""

  license: "MIT"
  licenseUrl: ""

management:
  endpoints:
    web:
      base-path: "/metrics"
      exposure:
        include: "*"

server:
  port: ${PORT:8002}

logging:
  level:
    ROOT: ${LOG_LEVEL:INFO}
    com.ibm.hello: DEBUG
    com.ibm.cloud_garage: DEBUG
    org.springframework: ERROR
    org.springframework.web: WARN
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    ch.qos.logback.classic: ERROR
  pattern:
    console: "%d{YYYY-dd-MM HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %X{X-B3-TraceId:-} ${spring.application.name} %logger{39}.%M %L - %msg%n"
---
spring:
  profiles: ocp
  cloud:
    stream:
      bindings:      
        cargoRoutingChannel:
          destination: cargoRoutings
          group: cargoRoutingsQueue
          contentType: 'application/json'
        cargoHandlingChannel1:
          destination: cargoHandlings1
          group: cargoHandlingsQueue1
          contentType: 'application/json'                                                   
                    
  datasource:
    url: ${trackingdburl}
    username: ${TRACKINGDB_USERNAME}
    password: ${TRACKINGDB_PASSWORD}
  rabbitmq:
    host: ${rabbitmqhost}
    port: ${rabbitmqport}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD} 

  application:
    name: "${IMAGE_NAME:template-spring-boot}"

swagger:
  baseApiPackage:
  - "com.cargotracker"
  - "com.ibm.health"
  title: "cargo-tracking-service"
  description: "cargo-tracking-service"
  version: "1.0.0"
  termsOfServiceUrl: ""

  license: "MIT"
  licenseUrl: ""

management:
  endpoints:
    web:
      base-path: "/metrics"
      exposure:
        include: "*"

server:
  port: ${PORT:8002}

logging:
  level:
    ROOT: ${LOG_LEVEL:INFO}
    com.ibm.hello: DEBUG
    com.ibm.cloud_garage: DEBUG
    org.springframework: ERROR
    org.springframework.web: WARN
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    ch.qos.logback.classic: ERROR
  pattern:
    console: "%d{YYYY-dd-MM HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %X{X-B3-TraceId:-} ${spring.application.name} %logger{39}.%M %L - %msg%n"
